<?php
 require_once 'manage.php';
   //require_once 'db.php';
   
    $query = new Manage();
    
  $q1 = $query->getQuestion(43, 4);
   $q2 = $query->getQuestion(44, 4);
    $q3 = $query->getQuestion(45, 4);
     $q4 = $query->getQuestion(46, 4);
      $q5 = $query->getQuestion(47, 4);
       $q6 = $query->getQuestion(48, 4); 
        $q7 = $query->getQuestion(48, 4);
         $q8 = $query->getQuestion(1, 1);
          $q9 = $query->getQuestion(2, 1);
           $q10 = $query->getQuestion(3, 1);
            $q11 = $query->getQuestion(4, 1);
             $q12 = $query->getQuestion(5, 1);
              $q13 = $query->getQuestion(6, 1);
               $q14 = $query->getQuestion(7, 1);
                $q15 = $query->getQuestion(8, 1);
                 $q16 = $query->getQuestion(9, 1);
                  $q17 = $query->getQuestion(10, 1);
                   $q18 = $query->getQuestion(11, 1);
                    $q19 = $query->getQuestion(12, 1);
                     $q20 = $query->getQuestion(13, 1);
                      $q21 = $query->getQuestion(14, 1);
                       $q22 = $query->getQuestion(15, 1);
                        $q23 = $query->getQuestion(16, 1);
                         $q24 = $query->getQuestion(17, 1);
                          $q25 = $query->getQuestion(18, 1);
                           $q26 = $query->getQuestion(19, 1);
                            $q27 = $query->getQuestion(20, 1);
                             $q28= $query->getQuestion(21, 1);
                              $q29 = $query->getQuestion(23, 2);
                               $q30= $query->getQuestion(24, 2);
                                $q31 = $query->getQuestion(25, 2);
                                 $q32 = $query->getQuestion(26, 2);
                                  $q33 = $query->getQuestion(27, 2);
                                   $q34 = $query->getQuestion(28, 2);
                                    $q35 = $query->getQuestion(29, 2);
                                     $q36 = $query->getQuestion(30, 2);
                                      $q37 = $query->getQuestion(31, 2);
                                       $q38 = $query->getQuestion(32, 2);
                                        $q39 = $query->getQuestion(33, 3);
                                         $q40 = $query->getQuestion(34, 3);
                                          $q41 = $query->getQuestion(35, 3);
                                           $q42 = $query->getQuestion(36, 3);
                                            $q43 = $query->getQuestion(37, 3);
                                             $q44 = $query->getQuestion(38, 3);
                                              $q45 = $query->getQuestion(39, 3);
                                               $q46 = $query->getQuestion(40, 3);
                                                $q47 = $query->getQuestion(41, 3);
                                                 $q48 = $query->getQuestion(42, 3);
       